### PR TITLE
Data script

### PR DESCRIPTION
**Pull request by olivialynn**
## Change Description

- [x] My PR includes a link to the issue that I am addressing

## Solution Description

A script to check for existence of data files and curl what is missing.

Required for rail_attic's [#372](https://github.com/LSSTDESC/rail_attic/pull/372) (fixing goldenspike pipeline); addresses rail_attic [#356](#356) (moving data) and rail [#26](#26) (moving demo files).

Notebooks that require data can curl directly within a cell, but additional care is needed in cases such as running a pipeline from command line.

This solution is proposed as a centralized and readable method to handle external data without requiring users to copy and paste a list of curl commands into their command line.

## Code Quality
- [x] I have read the Contribution Guide
- [x] My code follows the code style of this project
- [x] My code builds (or compiles) cleanly without any errors or warnings
- [x] My code contains relevant comments and necessary documentation

### New Feature Checklist
- [x] I have added or updated the docstrings associated with my feature using the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
**_(Will complete following, pending discussion resolution):_**
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover my new feature

### CODE REVIEW

**Review by drewoldag — APPROVED** [review]
This looks really useful!

**Comment by eacharles** [comment]
Maybe make this a part of the rail command line interface?  On Jun 27, 2023, at 6:24 PM, Olivia R. Lynn ***@***.***> wrote:﻿
Change Description


 My PR includes a link to the issue that I am addressing

Solution Description

A script to check for existence of data files and curl what is missing.
Required for rail_attic's #372 (fixing goldenspike pipeline); addresses rail_attic #356 (moving data) and rail #26 (moving demo files).
Notebooks that require data can curl directly within a cell, but additional care is needed in cases such as running a pipeline from command line.
This solution is proposed as a centralized and readable method to handle external data without requiring users to copy and paste a list of curl commands into their command line.
Code Quality

 I have read the Contribution Guide
 My code follows the code style of this project
 My code builds (or compiles) cleanly without any errors or warnings
 My code contains relevant comments and necessary documentation

Project-Specific Pull Request Checklists
New Feature Checklist

 I have added or updated the docstrings associated with my feature using the NumPy docstring format
(Will complete following, pending discussion resolution):
 I have updated the tutorial to highlight my new feature (if appropriate)
 I have added unit/End-to-End (E2E) test cases to cover my new feature




You can view, comment on, or merge this pull request online at:
  https://github.com/LSSTDESC/rail/pull/43

Commit Summary

  f782621  Initial script (with one file)


File Changes  (1 file)

  
    A
    get_data.py
    (35)
  


Patch Links:

  https://github.com/LSSTDESC/rail/pull/43.patch
  https://github.com/LSSTDESC/rail/pull/43.diff

**Comment by eacharles** [comment]
Maybe make this part of the rail command line interface?On Jun 27, 2023, at 7:43 PM, Drew Oldag ***@***.***> wrote:﻿
@drewoldag approved this pull request.

This looks really useful!

**Comment by olivialynn** [comment]
Thanks for the suggestion @eacharles, translated to a cli script in rail_base [(PR #20)](https://github.com/LSSTDESC/rail_base/pull/20)

**Pull request closed without merging**
