### PR TITLE
61 adding jupyter notebook for plotting and visualisation of dc2 and skysim simulations

### LINKED ISSUE #61: Adding jupyter notebook for plotting and visualisation of DC2 and skysim simulations
I would like to add into the creation_examples a new notebook where I implement plotting and visualization capabilities in RAIL  for DC2 and skysim simulations. 

The notebook addresses the following two items of my in-kind contribution:

- Implement visualization and plotting capabilities that interface with RAIL and the DC2 simulations (FY22Q4 and FY23Q1).
- Enable easy comparison of quantities of interest with DC2 data products (FY22Q4 and FY23Q1).

In this notebook, I'm going to compare colours and other properties between DC2, skysim and COSMOS, generate star-formation histories from skysim, generate SEDs with FSPS and DSPS, compare the results between the two codes, compare the resulting colours against COSMOS2020.

### PR DESCRIPTION
**Pull request by torluca**
This branch is meant to satisfy the requirement in my in-kind contribution of creating a plotting interface in RAIL with skysim and cosmoDC2.

### CODE REVIEW

**Comment by torluca** [comment]
To run the notebook, the user needs to have dsps, diffstar and jax installed. Maybe it would make more sense to move it into rail_dsps, what do you think?

**Review by eacharles — APPROVED** [review]
Thanks Luca

**Comment by aimalz** [comment]
> To run the notebook, the user needs to have dsps, diffstar and jax installed. Maybe it would make more sense to move it into rail_dsps, what do you think?

@torluca It seems that we've standardized on putting all notebooks in the central rail repo rather than the repos corresponding to the packages each notebook requires. It's nice to have them in one place because users can clone just the one repo to get all the demos, rather than cloning lots of them. However, the fact that vanilla rail's default installation includes only rail_base definitely detracts from the utility of having the notebooks centralized here. Please do chime in on the discussion in #29 if you have any thoughts on this setup.

**Comment by eacharles** [comment]
The vanilla installation is intended for something different.  (A truly vanilla installation where you add only the things you need by hand.).  The dev installation is intended for running notebooks.   On Oct 17, 2023, at 10:16 AM, Alex Malz ***@***.***> wrote:﻿

To run the notebook, the user needs to have dsps, diffstar and jax installed. Maybe it would make more sense to move it into rail_dsps, what do you think?

@torluca It seems that we've standardized on putting all notebooks in the central rail repo rather than the repos corresponding to the packages each notebook requires. It's nice to have them in one place because users can clone just the one repo to get all the demos, rather than cloning lots of them. However, the fact that vanilla rail's default installation includes only rail_base definitely detracts from the utility of having the notebooks centralized here. Please do chime in on the discussion in #29 if you have any thoughts on this setup.

**Pull request merged**
